### ISSUE TITLE
force font in css?

### ISSUE THREAD

**Issue by timelyportfolio** [MayaGans/githubCalendar#6]
Do you want to require users in https://github.com/MayaGans/githubCalendar/blob/master/inst/htmlwidgets/css/styles.css#L1 to use `arial`?  One option if you want to match the containing page/element would be to use `font-style: inherit;` https://developer.mozilla.org/en-US/docs/Web/CSS/inherit.  This would mean that in the case where a user has made a font choice, such as in `Rmd`, then the calendar will use the same font.

**Comment by MayaGans** [comment]
Ooh I like this!!

**Comment by MayaGans** [comment]
Closed with 30ea9038966a666713df: honestly I just wanted to play with attaching a css file inside the dependencies - this is a much better idea! 😊
